### PR TITLE
Adds NuGet build (build/build.bat)

### PR DESCRIPTION
**Pull request by nul800sebastiaan**
Version number needs to be maintained in build\version.txt now, the build will update it automatically in AssemblyInfo.cs

I don't know if there was a specific reason for chosing the build number that you have now, but I opted for normal SemVer notation here ([Major].[Minor].[Patch]).

By maintaining the build number in version.txt it's both easy to create a new version on local machine and on a build server. The build server can also pass in a different build number (add `-nightly123` for example).

Make sure to review the `.nuspec` file in case some information is not accurate. Someone else took it upon himself to publish an unofficial NuGet version already (https://www.nuget.org/packages/UrlRewritingNet/), so I set the id to the full name: `<id>UrlRewritingNet.UrlRewriter</id>`

### CODE REVIEW

**Comment by DerAlbertCom** [comment]
:+1:

**Comment by DerAlbertCom** [comment]
Thank you!

if there is an ongoing development in the future i can setup an Appveyor build.

**Comment by nul800sebastiaan** [comment]
@DerAlbertCom Already there ;-) https://ci.appveyor.com/project/SebastiaanJanssen/urlrewritingnet

**Comment by DerAlbertCom** [comment]
Great!

i'm contacting the owner of the current nuget package, to take over the ownership.

**Comment by nul800sebastiaan** [comment]
That's great, would certainly be better than uploading yet another package! If they are happy with that, the nuspec needs to be updated with the correct package id.

**Comment by nul800sebastiaan** [comment]
@DerAlbertCom Any news from them? I've tried to find information on "plusteam" but I can't find anything and they've not been active on NuGet since 2013. If you haven't heard from them I'd say we go ahead and publish the version with the full name as in this PR.

**Comment by DerAlbertCom** [comment]
No News, i will contact the nuget team to take over ownership.

**Comment by DerAlbertCom** [comment]
The Team Contacted the plusteam, also heard nothing. Will now take other steps ... so no progress yet. but i think we should wait another couple of days

**Comment by DerAlbertCom** [comment]
as we speak .. i'm now the owner of the package. i can add you so you can push the package, so your nuget.org username would be helpful.

**Comment by nul800sebastiaan** [comment]
Ha! Awesome, my username on github is just my first name: sebastiaan

**Comment by nul800sebastiaan** [comment]
Good stuff, all published!

> Downloading artifact build/UrlRewritingNet.2.0.7.nupkg to temporary location...OK
> Publishing UrlRewritingNet.2.0.7.nupkg to https://www.nuget.org/api/v2/package...OK
> Downloading artifact build/UrlRewritingNet.2.0.7.symbols.nupkg to temporary location...OK
> Publishing UrlRewritingNet.2.0.7.symbols.nupkg to http://nuget.gw.symbolsource.org/Public/NuGet...OK
> Total packages published: 2

**Comment by DerAlbertCom** [comment]
:+1:

**Pull request merged**
